config/routes.rb
Rails.application.routes.draw do
  devise_for :stores, controllers: {
    sessions:      'stores/sessions',
    passwords:     'stores/passwords',
    registrations: 'stores/registrations'
  }
  devise_for :farms, controllers: {
    sessions:      'farms/sessions',
    passwords:     'farms/passwords',
    registrations: 'farms/registrations'
  }
  root to: 'homes#index'
  resources :items do
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
    resources :likes, only: [:create, :destroy]
  end
  resources :farms, only: :show
  resources :stores, only: :show do
    collection do
      get 'like'
    end
  end
  resources :homes, only: :index
end

app/models/store.rb
class Store < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :likes, dependent: :destroy
  has_many :like_items, through: :likes, source: :item
  has_one_attached :image

  with_options presence: true do
    validates :image
    validates :first_name
    validates :last_name
    validates :first_name_kana
    validates :last_name_kana
    validates :nickname
    validates :email
    validates :password, format: { with: /\A[a-z0-9]+\z/i, message: 'は半角英数字で入力してください' }
    validates :password_confirmation, format: { with: /\A[a-z0-9]+\z/i, message: 'は半角英数字で入力してください' }
    with_options length: { maximum: 10, message: 'は10文字以下で入力してください' } do
      validates :first_name
      validates :last_name
      validates :first_name_kana
      validates :last_name_kana
      with_options format: { with: /\A[一-龥]+\z/, message: 'は漢字で入力してください' } do
        validates :first_name
        validates :last_name
      end
      with_options format: { with: /\A[ァ-ヶー－]+\z/, message: 'はカタカナで入力してください' } do
        validates :first_name_kana
        validates :last_name_kana
      end
    end
    with_options uniqueness: { case_sensitive: true, message: 'は既に登録されています' } do
      validates :email
    end
  end

  def liked_by?(item)
    likes.where(item_id: item.id).exists?
  end
end

app/controllers/stores/confirmations_controller.rb
# frozen_string_literal: true

class Stores::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/stores/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Stores::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/stores/passwords_controller.rb
# frozen_string_literal: true

class Stores::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/stores/registrations_controller.rb
# frozen_string_literal: true

class Stores::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/stores/sessions_controller.rb
# frozen_string_literal: true

class Stores::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/stores/unlocks_controller.rb
# frozen_string_literal: true

class Stores::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :move_to_login
  def show
    store = Store.find(params[:id])
    @nickname = store.nickname
    @email = store.email
    @orders = store.orders
    @items = store.item_id
    @image = store.image
    likes = Like.where(store_id: store.id).pluck(:item_id)
    @like_items = Item.find(likes)
  end

  private

  def move_to_login
    redirect_to store_session_path unless store_signed_in?
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/show.html.erb
<div class="main-wrapper">

  <%= render "shared/side"%>
  <div class="store-show-main">
    <div class="store-show-box">
      <% if store_signed_in?%>
        <% if @email == current_store.email %>
          <div class="store-show-status-box">
            <div class="store-status">
              <div class="item-img-content">
                <%= image_tag @image, class:"item-box-img" %>
              </div>
              <h2 class="store-nickname"> 
                <%= @nickname %>
              </h2>
              <p class="store-email">
                <%= @email %>
              </p>
              <div class="store-select-btn-container">
                <%# <div class="store-edit-btn">
                  <%= link_to "編集", "/stores/edit" %> 
                <%# </div>  %>
                <%# <div class="store-delete-btn">
                  <%= link_to "退会", store_registration_path, method: :delete %> 
                <%# </div> %>
              </div>
            </div>
          </div>
          <div class="store-show">
            <h2 class="main-title"><%= @nickname %>さんの購入商品一覧</h2>
            <ul class="store-item-lists">
              <% @orders.each do |order| %>
                <li class="store-item-list">
                  <%= link_to item_path(order.item.id) do %>
                    <div class="item-img-content">
                      <%= image_tag order.item.image, class: "item-images"%> 
                    </div>
                    <div class='item-info'>
                      <h3 class='item-name'>
                        <%= "#{order.item.product}" %>
                      </h3>
                      <div class='item-price'>
                        <span><%= "#{order.item.price}" %>
                        円<br><%= "#{order.item.shipping_fee.name}" %> 
                        </span>  
                      </div>
                    </div>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
          <div class="store-like-show">
            <h2 class="main-title"><%= @nickname %>さんのお気に入り商品一覧</h2>
            <ul class="store-item-lists">
              <% @like_items.each do |like| %>
                <li class="store-item-list">
                  <%= link_to item_path(like.id) do %>
                    <div class="item-img-content">
                      <%= image_tag like.image, class: "item-images"%>
                      <% if like.order.present? %>
                        <div class="sold-out">
                          <span>売却済み</span>
                        </div>
                      <% end %>
                    </div>
                    <div class='item-info'>
                      <h3 class='item-name'>
                        <%= "#{like.product}" %>
                      </h3>
                      <div class='item-price'>
                        <span><%= "#{like.price}" %>
                        円<br><%= "#{like.shipping_fee.name}" %> 
                        </span>  
                      </div>
                    </div>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>