config/routes.rb
Rails.application.routes.draw do
  devise_for :stores, controllers: {
    sessions:      'stores/sessions',
    passwords:     'stores/passwords',
    registrations: 'stores/registrations'
  }
  devise_for :farms, controllers: {
    sessions:      'farms/sessions',
    passwords:     'farms/passwords',
    registrations: 'farms/registrations'
  }
  root to: 'homes#index'
  resources :items do
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
    resources :likes, only: [:create, :destroy]
  end
  resources :farms, only: :show
  resources :stores, only: :show do
    collection do
      get 'like'
    end
  end
  resources :homes, only: :index
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :states
  belongs_to :shipping_fee
  belongs_to :region
  belongs_to :eta
  belongs_to :farm
  has_one :order
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :like_stores, through: :likes, source: :store
  # has_many_attached :images

  with_options presence: true do
    validates :image
    validates :product
    validates :category_id, numericality: { other_than: 1, message: 'を選択してください' }
    validates :states_id, numericality: { other_than: 1, message: 'を選択してください' }
    validates :shipping_fee_id, numericality: { other_than: 1, message: 'を選択してください' }
    validates :region_id, numericality: { other_than: 1, message: 'を選択してください' }
    validates :eta_id, numericality: { other_than: 1, message: 'を選択してください' }, format: { with: /\A[0-9]+\z/ }
    validates :price, format: { with: /\A[0-9]+\z/ }, numericality: { only_integer: true,
                                                                      greater_than: 49, less_than: 10_000_000,
                                                                      message: 'は50~9,999,999の半角数字で入力してください' }
  end

  def self.search(search)
    if search != ''
      Item.where('product LIKE(?)', "%#{search}%")
    else
      Item.all
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]
  before_action :set_item, except: [:index, :new, :create, :search]
  def index
    @items = Item.includes(:user)
    @items = Item.page(params[:page]).per(10)
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    # 画像複数枚投稿実装の時使用
    # if params[:item][:image_ids]
    #   params[:item][:image_ids].each do |image_id|
    #     image = @item.images.find(image_id)
    #     image.purge
    #   end
    # end
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to items_path if @item.destroy
  end

  def search
    @items = Item.search(params[:keyword])
  end

  private

  def item_params
    params.require(:item).permit(:product, :description, :category_id, :states_id,
                                 :shipping_fee_id, :region_id, :eta_id, :price, :image).merge(farm_id: current_farm.id)
  end

  def move_to_index
    redirect_to action: :index unless farm_signed_in?
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="main-wrapper">

  <%= render "shared/side"%>

  <div class="edit-main">
    <div class="edit-container">
      <h2 class="edit-title">商品の情報を入力</h2>
      <%= form_with model: @item, class: "edit-form", local: true  do |f| %>

      <%= render 'shared/error', model: f.object %>

      <div class="img-upload">
        <div class="weight-bold-text">
          出品画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            変更する場合は、ファイルを選択してください<br>変更しない場合はそのままで大丈夫です
          </p>
          <%= f.file_field :image ,id: "item-edit-image" %>
        </div>
      </div>     
      <div id="image-edit-list"></div>
      <% image_tag @item.image, id: "edit-image" if @item.image.present? %>
      <div class="edit-items">
        <div class="weight-bold-text">
          商品名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :product, class:"items-text", id:"item-edit-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"items-text", id:"item-edit-info", placeholder:"商品の説明（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <div class="items-detail">
        <div class="weight-bold-text">商品の詳細</div>
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-edit-category"}) %>
          <div class="weight-bold-text">
            商品の状態
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:states_id, States.all, :id, :name, {}, {class:"select-box", id:"item-edit-sales-status"}) %>
        </div>
      </div>
      <div class="items-delivery-detail">
        <div class="weight-bold-text">
          <span>配送について</span>
        </div>
        <div class="form">
          <div class="weight-bold-text">
            配送料の負担
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:shipping_fee_id, ShippingFee.all, :id, :name, {}, {class:"select-box", id:"item-edit-shipping-fee-status"}) %>
          <div class="weight-bold-text">
            発送元の地域
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:region_id, Region.all, :id, :name, {}, {class:"select-box", id:"item-edit-region"}) %> 
          <div class="weight-bold-text">
            発送までの日数
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:eta_id, Eta.all, :id, :name, {}, {class:"select-box", id:"item-edit-eta"}) %>
        </div>
      </div>
      <div class="sell-price">
        <div class="weight-bold-text">
          <span>販売価格<br>(¥10〜9,999,999)</span>
        </div>
        <div class="price-contents">
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
              <span class="indispensable">必須</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-edit-price", placeholder:"例）300" %>
          </div>
          <div class="price-content">
            <span>販売手数料 (10%)</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
          <div class="price-content">
            <span>販売利益</span>
            <span>
              <span id='profit'></span>円
          </div>
          </span>
          <%# 後で使用する %>
          <%# <script src="javascript/price.js"></script> %>
        </div>
      </div>
      <div class="sell-btn-contents">
        <div class="sell-btn-content">
          <%= f.submit "変更する", class:"edit-btn" %>
        </div>
        <div class="back-btn-content">
          <%=link_to '戻る', items_path, class:"back-btn" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/items/index.html.erb
<div class="main-wrapper">
  
  <%= render "shared/side"%>
  
  <div class="item-contents">
    <h2 class="main-title">商品一覧</h2>
    <ul class="item-lists">
      <% @items.each do |item| %>
        <li class="list">
          <%= link_to item_path(item.id) do %>
            <div class="item-img-content">
              <%= image_tag item.image, class: "item-images" if item.image.present? %>
              <% if item.order.present? %>
                <div class='sold-out'>
                  <span>売却済み</span>
                </div> 
              <% end %>
            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= "#{item.product}" %>
              </h3>
              <div class='item-price'>
                <span><%= "#{item.price}" %>
                円<br><%= "#{item.shipping_fee.name}" %>
                </span>  
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
      <% if @items.length == 0 %> 
        <li class='list'>
          <%= link_to '#' do %>
            <div class="item-img-content">
              <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-images" %> 
            </div>  
            <div class='item-info'>
              <h3 class='item-name'>
                  商品を出品してださい。
              </h3>
              <div class='item-price'>
                <span>99999999円<br>(税込み)</span>
              </div>
            </div> 
          <% end %> 
        </li>
      <% end %> 
    </ul>
    <div class="page-container">
      <%= paginate @items, class: "page" %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="main-wrapper">

  <%= render "shared/side"%>

  <div class="sell-main">
    <div class="sell-container">
      <h2 class="sell-title">商品の情報を入力</h2>
      <%= form_with model: @item, class: "sell-form", local: true  do |f| %>
    
      <%= render 'shared/error', model: f.object %>
        
        <div class="img-upload">
          <div class="weight-bold-text">
            出品画像
            <span class="indispensable">必須</span>
          </div>
          <div class="click-upload" id="click-upload">
            <%= f.file_field :image, id: "item-image" %>
          </div>
        </div>
        <div id="image-list"></div>
        <% image_tag @item.image, id: "image" if @item.image.present? %>
        <div class="new-items">
          <div class="weight-bold-text">
            商品名
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :product, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        </div>
        <div class="items-explain">
          <div class="weight-bold-text">
            商品の説明
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :description, class:"items-text", id:"item-info", placeholder: "注)カテゴリーで複数種混合を選択した場合は内容を説明欄に記載してください（必須 1,000文字まで)" , rows:"7" , maxlength:"1000" %>
        </div>
        <div class="items-detail">
          <div class="weight-bold-text">商品の詳細</div>
          <div class="form">
            <div class="weight-bold-text">
              カテゴリー
              <span class="indispensable">必須</span>
            </div>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
            <div class="weight-bold-text">
              商品の状態
              <span class="indispensable">必須</span>
            </div>
            <%= f.collection_select(:states_id, States.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
          </div>
        </div>
        <div class="items-delivery-detail">
          <div class="weight-bold-text">
            <span>配送について</span>
          </div>
          <div class="form">
            <div class="weight-bold-text">
              配送料の負担
              <span class="indispensable">必須</span>
            </div>
            <%= f.collection_select(:shipping_fee_id, ShippingFee.all, :id, :name, {}, {class:"select-box", id:"item-shipping-fee-status"}) %>
            <div class="weight-bold-text">
              発送元の地域
              <span class="indispensable">必須</span>
            </div>
            <%= f.collection_select(:region_id, Region.all, :id, :name, {}, {class:"select-box", id:"item-region"}) %> 
            <div class="weight-bold-text">
              発送までの日数
              <span class="indispensable">必須</span>
            </div>
            <%= f.collection_select(:eta_id, Eta.all, :id, :name, {}, {class:"select-box", id:"item-eta"}) %>
          </div>
        </div>
        <div class="sell-price">
          <div class="weight-bold-text">
            <span>販売価格(¥10〜9,999,999)</span>
          </div>
          <div class="price-contents">
            <div class="price-content">
              <div class="price-text">
                <span>価格</span>
                <span class="indispensable">必須</span>
              </div>
              <span class="sell-yen">¥</span>
              <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
            </div>
            <div class="price-content">
              <span>販売手数料 (10%)</span>
              <span>
                <span id='add-tax-price'></span>円
              </span>
            </div>
            <div class="price-content">
              <span>販売利益</span>
              <span>
                <span id='profit'></span>円
            </div>
            </span>
            <%# 後で使用する %>
            <%# <script src="javascript/price.js"></script> %>
          </div>
        </div>
        <div class="sell-btn-contents">
          <div class="sell-btn-content">
            <%= f.submit "出品する", class:"sell-btn" %>
          </div>
          <div class="back-btn-content">
            <%=link_to '戻る', items_path, class:"back-btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/search.html.erb
<div class="main-wrapper">

  <%= render "shared/side"%>

  <div class="item-contents">
    <h2 class="main-title">検索一覧</h2>
    <ul class="item-lists">
      <% @items.each do |item| %>
        <li class="list">
          <%= link_to item_path(item.id) do %>
          <div class="item-img-content">
            <%= image_tag item.image, class: "item-images" %>
            <% if item.order.present? %>
              <div class='sold-out'>
                <span>売却済み</span>
              </div> 
            <% end %> 
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= "#{item.product}" %>
            </h3>
            <div class='item-price'>
              <span><%= "#{item.price}" %>
              円<br><%= "#{item.shipping_fee.name}" %>
              </span>  
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>

app/views/items/show.html.erb
<div class="main-wrapper">

  <%= render "shared/side"%>
  
  <div class="item-show">
    <div class="item-show-container">
      <div class="item-box">
        <h2 class="item-show-name">
          <%= "#{@item.product}" %>
        </h2>
        <div class="item-img-content">
          <%= image_tag @item.image, class:"item-box-img" %>
          <% if @item.order.present? %>
            <div class="sold-out">
              <span>売却済み</span>
            </div>
          <% end %>
        </div>
        <div class="item-price-box">
          <div class="item-price">
            <span>
              <%= "￥#{@item.price}" %>
            </span>
          </div>
          <div class="item-postage">
            <%= "#{@item.shipping_fee.name}" %>
          </div>
        </div>

        <%= render('likes/like',item: @item) %>

        <div class="item-command">
          <% if farm_signed_in? && @item.order == nil %>
            <% if current_farm.id == @item.farm_id %>
              <%= link_to "編集", edit_item_path(@item.id), method: :get, class: "item-edit-btn" %>
              <p class="or-text">or</p>
              <%= link_to "削除", item_path(@item.id), method: :delete, class: "item-destroy-btn" %>
            <% end %>
          <% elsif store_signed_in? && @item.order == nil %>
            <% if current_store.id %>
              <%= link_to "購入する", item_orders_path(@item.id), class: "item-order-btn" %>
            <% end %>
          <% elsif @item.order != nil %>
          <%# 何も表示しないという表示 %>
          <%# /何も表示しないという表示 %>
          <% else %>
              <%= link_to "売る", new_farm_session_path, class: "item-edit-btn" %>
              <p class="or-text">or</p>
              <%= link_to "買う", new_store_session_path, class: "item-destroy-btn" %>
          <% end %>
        </div>
        <div class="item-description-box">
          <span><%= "#{@item.description}" %></span>
        </div>
        <table class="detail-table">
          <tbody>
            <tr>
              <th class="detail-item">出品者</th>
              <td class="detail-value">
              <%= link_to "#{@item.farm.nickname}", farm_path(@item.farm.id), class: "show-farm-name" %>
              </td>
            </tr>
            <tr>
              <th class="detail-item">カテゴリー</th>
              <td class="detail-value"><%= "#{@item.category.name}" %></td>
            </tr>
            <tr>
              <th class="detail-item">商品の状態</th>
              <td class="detail-value"><%= "#{@item.states.name}" %></td>
            </tr>
            <tr>
              <th class="detail-item">配送料の負担</th>
              <td class="detail-value"><%= "#{@item.shipping_fee.name}" %></td>
            </tr>
            <tr>
              <th class="detail-item">発送元の地域</th>
              <td class="detail-value"><%= "#{@item.region.name}" %></td>
            </tr>
            <tr>
              <th class="detail-item">発送日の目安</th>
              <td class="detail-value"><%= "#{@item.eta.name}" %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
    