config/routes.rb
Rails.application.routes.draw do
  devise_for :stores, controllers: {
    sessions:      'stores/sessions',
    passwords:     'stores/passwords',
    registrations: 'stores/registrations'
  }
  devise_for :farms, controllers: {
    sessions:      'farms/sessions',
    passwords:     'farms/passwords',
    registrations: 'farms/registrations'
  }
  root to: 'homes#index'
  resources :items do
    resources :orders, only: [:index, :create]
    collection do
      get 'search'
    end
    resources :likes, only: [:create, :destroy]
  end
  resources :farms, only: :show
  resources :stores, only: :show do
    collection do
      get 'like'
    end
  end
  resources :homes, only: :index
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BuyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <div class="header-bar">
        <div class="header-left">
          <ul >
            <%= link_to root_path ,id: "logo" do %>
              <li class="logo">ワ</li>
              <li class="logo">ケ</li>
              <li class="logo">ア</li>
              <li class="logo">リ</li>
            <% end %>
          </ul>
        </div>
        <div class="header-right">
          <div class="header-upper">
            <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |f| %>
              <%= f.text_field :keyword, placeholder: "商品を検索する", class: "search-text-form" %>
              <%= f.submit "検索", class: "search-btn" %>
            <% end %>
          </div>
          <div class="header-down">
            <% if farm_signed_in? %>
              <%= link_to "#{current_farm.nickname}さん", "/farms/#{current_farm.id}", class: "user-name", id: "name-btn" %>
              <%= link_to "ログアウト", destroy_farm_session_path, class: "logout", id: "logout-btn", method: :delete %>
              <%= link_to "商品一覧", items_path, class: "item-container" %> 
              <%= link_to "出品", "/items/new/", class: "new-item" %> 
            <% elsif store_signed_in? %>
              <%= link_to "#{current_store.nickname}さん", "/stores/#{current_store.id}", class: "user-name", id: "name-btn" %>
              <%= link_to "ログアウト", destroy_store_session_path, class: "logout", id: "logout-btn", method: :delete %>
              <%= link_to "商品一覧", items_path, class: "item-container" %> 
            <% else %>
            <div class="user-select" id="farm-select" >
              出品者様はこちら
              <ul class="farm-more-lists hidden" id="farm-pull-down">
                <li class="more-list" id="list-farm-login">
                  <%= link_to "出品者ログイン", new_farm_session_path, class: "login", id: "farm-login-btn" %>
                </li>
                <li class="more-list" id="list-farm-sign-up">
                  <%= link_to "出品者新規登録", new_farm_registration_path, class: "sign-up", id: "farm-signup-btn" %>
                </li>
              </ul> 
            </div>
            <div class="user-select" id="store-select">
              購入者様はこちら
              <ul class="store-more-lists hidden" id="store-pull-down">
                <li class="more-list" id="list-store-login">
                  <%= link_to "購入者ログイン", new_store_session_path, class: "login", id: "store-login-btn" %>
                </li>
                <li class="more-list" id="list-store-sign-up">
                  <%= link_to "購入者新規登録", new_store_registration_path, class: "sign-up", id: "store-signup-btn" %>
                </li>
              </ul>
            </div>
            <div class="item-container-box">
              <%= link_to "商品一覧", items_path, class: "item-container", id: "item-box" %>
            <div>
            <% end %> 
          </div>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="footer-bar">
        <div class="footer-word"> ~ワケアリ~ </div>
      </div>
    </footer>
  </body>
</html>